import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        
        {/* Telegram widget script */}
        <script async src="https://telegram.org/js/telegram-widget.js?22" data-telegram-login="rafahKhanvadah_bot" data-size="large" data-radius="20" data-onauth="onTelegramAuth(user)" data-request-access="write"></script>
        <script type="text/javascript">
          {`
            function onTelegramAuth(user) {
              alert('Logged in as ' + user.first_name + ' ' + user.last_name + ' (' + user.id + (user.username ? ', @' + user.username : '') + ')');
            }
          `}
        </script>
      </body>
    </html>
  );
}
